templates/sshd_config.erb

no nothing, just beautifying the output file

move empty line into conditional block

---

manifests/init.pp
spec/classes/init_spec.rb

Remove if statement for sshd_gssapiauthentication to avoid undef.

Remove if statement for sshd_gssapiauthentication.

---

README.md
manifests/init.pp
spec/classes/init_spec.rb
templates/sshd_config.erb

Hopefully this time not with so many problems as last time. :)

Parameterize IgnoreUserKnownHosts & IgnoreRhosts

---

.fixtures.yml
.gitignore
.travis.yml
manifests/init.pp
metadata.json
spec/classes/init_spec.rb
spec/fixtures/hiera/hiera.yaml
spec/fixtures/hiera/hieradata/common.yaml
spec/fixtures/hiera/hieradata/fqdn/hieramerge.example.com.yaml
spec/fixtures/hiera/hieradata/fqdn/monkey.example.com.yaml
spec/spec_helper.rb
templates/sshd_config.erb

fix failing spec tests

---

README.md
manifests/init.pp
metadata.json
spec/classes/init_spec.rb

On SLES 12 the SFTP subsystem changed the path.

add default SFTP subsystem for SLES12

---

README.md

This makes the markup render nicely on GitHub

Change formatting in README to be explicit about example types

---

README.md
manifests/init.pp
spec/classes/init_spec.rb
templates/ssh_config.erb

Please look into the change and see if it's ok for merging

Add support for UserKnownHostsFile and add multiple files support for GlobalKnownHostsFile

---

README.md
manifests/init.pp
spec/classes/init_spec.rb
spec/fixtures/sshd_config_debian
spec/fixtures/sshd_config_rhel
spec/fixtures/sshd_config_sles_12_x86_64
spec/fixtures/sshd_config_solaris
spec/fixtures/sshd_config_suse_i386
spec/fixtures/sshd_config_suse_x86_64
spec/fixtures/sshd_config_ubuntu1604
templates/sshd_config.erb

Setting requested by LSF users for submitting X-based jobs via LSF.

Add configurable param X11UseLocalhost to sshd_config

---

README.md
manifests/init.pp
spec/classes/init_spec.rb
templates/ssh_config.erb
templates/sshd_config.erb

This allows for the KexAlgorithms option to be added to ssh_config and sshd_config

adding support for KexAlgorithms

---

.travis.yml
README.md
manifests/init.pp
spec/classes/init_spec.rb
spec/fixtures/sshd_config_solaris
templates/sshd_config.erb

Suggestion for a fix of issue https://github.com/ghoneycutt/puppet-module-ssh/issues/208

Fix parameters not compatible with Solaris

---

metadata.json

Update concat dependency to be compatible with concat 3.x and 4.x

---

manifests/init.pp
spec/classes/init_spec.rb
spec/fixtures/sshd_config_rhel7

Disable ServerkeyBits on RHEL 7.4 and later

---

README.md
manifests/init.pp
spec/classes/init_spec.rb
templates/sshd_config.erb

Co-authored-by: Garrett Honeycutt <code@garretthoneycutt.com>

Add RevokedKeys option to sshd_config

---

metadata.json

Allow puppetlabs-concat < 6.0.0

---

Rakefile
spec/classes/init_spec.rb

Not sure when this behavior changed...

Explicitly unset the ipaddress6 fact

---

.fixtures.yml

Test stdlib 9.x with regular unit tests

---

UPGRADING.md

Fix option name to match template https://github.com/ghoneycutt/puppet-module-ssh/blob/v4.1.0/templates/sshd_config.erb#L56-L58

(docs) Fix ChallengeResponseAuthentication Option

---

spec/classes/init_params_spec.rb
templates/ssh_config.erb

Multiple files will create one IdentityFile line for each file.
Fix #399

Fix for multiple IdentityFile files

---

manifests/server.pp
spec/classes/server_data_types_spec.rb
spec/classes/server_params_spec.rb
templates/sshd_config.erb

Multiple files will create one HostCertificate line for each file.
Fixes #391

Fix for multiple HostCertificate files

---

manifests/init.pp
manifests/server.pp
spec/classes/init_spec.rb
spec/classes/server_spec.rb

Taking over the work and idea of @jovandeginste from https://github.com/ghoneycutt/puppet-module-ssh/pull/328.
+ rebased against v4 branch
+ added parameter to the server class too
+ added unit tests
Taking over the work and idea of @sethlyons fromt https://github.com/ghoneycutt/puppet-module-ssh/pull/351.
+ rebased against v4 branch
+ added unit tests

Add $package_ensure to package resources and option to manage packages

---

manifests/server.pp

Update documentation to use correct link to man page

---

manifests/config_file_server.pp
manifests/server.pp
spec/classes/server_spec.rb
spec/defines/config_file_server_spec.rb
spec/fixtures/testing/Debian-11_sshd_config
spec/fixtures/testing/RedHat-9_sshd_config
spec/fixtures/testing/Ubuntu-20.04_sshd_config
spec/fixtures/testing/Ubuntu-22.04_sshd_config
templates/sshd_config.erb

Put Include directive first
Replaces #409 and #413
Fixes #407
Fixes #408

Notify sshd when conf.d files change
